name: Build Android

on:
  push:

jobs:

  build:
    runs-on: ubuntu-latest-8core
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up NDK
      uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r24
        local-cache: true
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.1'
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'
    - name: Build imessage.so
      run: ./android/imessage.sh
    - name: Build AAR
      run: ./android/gradlew -p android :library:assembleRelease
    - name: Publish to GitHub Packages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: ./android/gradlew -p android :library:publish
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: aar
        path: ./android/library/build/outputs/aar/library-release.aar
